# Generated by Django 3.2 on 2025-03-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='S0n09EIh8BRjpUVOHZbh6js4iIlXz4CZ', editable=False, max_length=100, unique=True),
        ),
    ]
