# Generated by Django 3.2 on 2025-03-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='8Mh634Rsf5JjbK1AAjRAyvZ5xHcPv99g', editable=False, max_length=100, unique=True),
        ),
    ]
