# Generated by Django 3.2 on 2025-03-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_auto_20250312_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Ywjie09vXQqlBHIMvRRyzjSiINQHAtkT', editable=False, max_length=100, unique=True),
        ),
    ]
