# Generated by Django 3.2 on 2025-03-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='0mlqBGtWFKN2C234YiZCa87vB0OfQi7O', editable=False, max_length=100, unique=True),
        ),
    ]
